targetUrl: http://localhost:8080
urlExpression: headers.http_requestUrl.replaceAll('https*://[^/]*/tunnel','${targetUrl}')
server.port: 9000

---

spring:
  profiles: default,server
inboundQueue: server
outboundQueue: client
 
---

spring:
  profiles: client
inboundQueue: client
outboundQueue: server

---

spring:
  profiles: test
inboundQueue: request
outboundQueue: request

---

spring:
  profiles: cloud
  